package com.dengji85.blog.mapper;

import com.dengji85.blog.model.Actress;
import com.dengji85.blog.model.ActressExample;
import com.dengji85.blog.param.ActressParam;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ActressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int countByExample(ActressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int deleteByExample(ActressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int insert(Actress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int insertSelective(Actress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    List<Actress> selectByExampleWithRowbounds(ActressExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    List<Actress> selectByExample(ActressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    Actress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Actress record, @Param("example") ActressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Actress record, @Param("example") ActressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Actress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Actress record);
    Actress searchByParam (ActressParam param);
}