package com.dengji85.blog.mapper;

import com.dengji85.blog.model.TimeLine;
import com.dengji85.blog.model.TimeLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TimeLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int countByExample(TimeLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int deleteByExample(TimeLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int insert(TimeLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int insertSelective(TimeLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    List<TimeLine> selectByExampleWithRowbounds(TimeLineExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    List<TimeLine> selectByExample(TimeLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    TimeLine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TimeLine record, @Param("example") TimeLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TimeLine record, @Param("example") TimeLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TimeLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TimeLine record);
}