package com.dengji85.blog.mapper;

import com.dengji85.blog.model.Visit;
import com.dengji85.blog.model.VisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int countByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int deleteByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int insert(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int insertSelective(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    List<Visit> selectByExampleWithRowbounds(VisitExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    List<Visit> selectByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    Visit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Visit record, @Param("example") VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Visit record, @Param("example") VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Visit record);
}