package com.dengji85.blog.model;

import java.util.Date;

public class Actress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.ACTRESS_NAME
     *
     * @mbggenerated
     */
    private String actressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.BIRTHDAY
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.HIPLINE
     *
     * @mbggenerated
     */
    private String hipline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.BUST
     *
     * @mbggenerated
     */
    private String bust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.WAISTLINE
     *
     * @mbggenerated
     */
    private String waistline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.CUP
     *
     * @mbggenerated
     */
    private String cup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.HEIGHT
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.HOBBY
     *
     * @mbggenerated
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.HOME_PLACE
     *
     * @mbggenerated
     */
    private String homePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.ADD_TIME
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.ADD_USER
     *
     * @mbggenerated
     */
    private Long addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.MOD_USER
     *
     * @mbggenerated
     */
    private Long modUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.MOD_TIME
     *
     * @mbggenerated
     */
    private Date modTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.DEL_FLAG
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.IS_MY
     *
     * @mbggenerated
     */
    private Integer isMy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.MY_STAR
     *
     * @mbggenerated
     */
    private Integer myStar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actress.IMG
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.ID
     *
     * @return the value of actress.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.ID
     *
     * @param id the value for actress.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.ACTRESS_NAME
     *
     * @return the value of actress.ACTRESS_NAME
     *
     * @mbggenerated
     */
    public String getActressName() {
        return actressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.ACTRESS_NAME
     *
     * @param actressName the value for actress.ACTRESS_NAME
     *
     * @mbggenerated
     */
    public void setActressName(String actressName) {
        this.actressName = actressName == null ? null : actressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.BIRTHDAY
     *
     * @return the value of actress.BIRTHDAY
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.BIRTHDAY
     *
     * @param birthday the value for actress.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.HIPLINE
     *
     * @return the value of actress.HIPLINE
     *
     * @mbggenerated
     */
    public String getHipline() {
        return hipline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.HIPLINE
     *
     * @param hipline the value for actress.HIPLINE
     *
     * @mbggenerated
     */
    public void setHipline(String hipline) {
        this.hipline = hipline == null ? null : hipline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.BUST
     *
     * @return the value of actress.BUST
     *
     * @mbggenerated
     */
    public String getBust() {
        return bust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.BUST
     *
     * @param bust the value for actress.BUST
     *
     * @mbggenerated
     */
    public void setBust(String bust) {
        this.bust = bust == null ? null : bust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.WAISTLINE
     *
     * @return the value of actress.WAISTLINE
     *
     * @mbggenerated
     */
    public String getWaistline() {
        return waistline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.WAISTLINE
     *
     * @param waistline the value for actress.WAISTLINE
     *
     * @mbggenerated
     */
    public void setWaistline(String waistline) {
        this.waistline = waistline == null ? null : waistline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.CUP
     *
     * @return the value of actress.CUP
     *
     * @mbggenerated
     */
    public String getCup() {
        return cup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.CUP
     *
     * @param cup the value for actress.CUP
     *
     * @mbggenerated
     */
    public void setCup(String cup) {
        this.cup = cup == null ? null : cup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.HEIGHT
     *
     * @return the value of actress.HEIGHT
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.HEIGHT
     *
     * @param height the value for actress.HEIGHT
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.HOBBY
     *
     * @return the value of actress.HOBBY
     *
     * @mbggenerated
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.HOBBY
     *
     * @param hobby the value for actress.HOBBY
     *
     * @mbggenerated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.HOME_PLACE
     *
     * @return the value of actress.HOME_PLACE
     *
     * @mbggenerated
     */
    public String getHomePlace() {
        return homePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.HOME_PLACE
     *
     * @param homePlace the value for actress.HOME_PLACE
     *
     * @mbggenerated
     */
    public void setHomePlace(String homePlace) {
        this.homePlace = homePlace == null ? null : homePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.ADD_TIME
     *
     * @return the value of actress.ADD_TIME
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.ADD_TIME
     *
     * @param addTime the value for actress.ADD_TIME
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.ADD_USER
     *
     * @return the value of actress.ADD_USER
     *
     * @mbggenerated
     */
    public Long getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.ADD_USER
     *
     * @param addUser the value for actress.ADD_USER
     *
     * @mbggenerated
     */
    public void setAddUser(Long addUser) {
        this.addUser = addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.MOD_USER
     *
     * @return the value of actress.MOD_USER
     *
     * @mbggenerated
     */
    public Long getModUser() {
        return modUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.MOD_USER
     *
     * @param modUser the value for actress.MOD_USER
     *
     * @mbggenerated
     */
    public void setModUser(Long modUser) {
        this.modUser = modUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.MOD_TIME
     *
     * @return the value of actress.MOD_TIME
     *
     * @mbggenerated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.MOD_TIME
     *
     * @param modTime the value for actress.MOD_TIME
     *
     * @mbggenerated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.DEL_FLAG
     *
     * @return the value of actress.DEL_FLAG
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.DEL_FLAG
     *
     * @param delFlag the value for actress.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.TYPE
     *
     * @return the value of actress.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.TYPE
     *
     * @param type the value for actress.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.IS_MY
     *
     * @return the value of actress.IS_MY
     *
     * @mbggenerated
     */
    public Integer getIsMy() {
        return isMy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.IS_MY
     *
     * @param isMy the value for actress.IS_MY
     *
     * @mbggenerated
     */
    public void setIsMy(Integer isMy) {
        this.isMy = isMy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.MY_STAR
     *
     * @return the value of actress.MY_STAR
     *
     * @mbggenerated
     */
    public Integer getMyStar() {
        return myStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.MY_STAR
     *
     * @param myStar the value for actress.MY_STAR
     *
     * @mbggenerated
     */
    public void setMyStar(Integer myStar) {
        this.myStar = myStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actress.IMG
     *
     * @return the value of actress.IMG
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actress.IMG
     *
     * @param img the value for actress.IMG
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}