package com.dengji85.blog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actress
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actress
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actress
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public ActressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actress
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table actress
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActressNameIsNull() {
            addCriterion("ACTRESS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andActressNameIsNotNull() {
            addCriterion("ACTRESS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andActressNameEqualTo(String value) {
            addCriterion("ACTRESS_NAME =", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameNotEqualTo(String value) {
            addCriterion("ACTRESS_NAME <>", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameGreaterThan(String value) {
            addCriterion("ACTRESS_NAME >", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTRESS_NAME >=", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameLessThan(String value) {
            addCriterion("ACTRESS_NAME <", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameLessThanOrEqualTo(String value) {
            addCriterion("ACTRESS_NAME <=", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameLike(String value) {
            addCriterion("ACTRESS_NAME like", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameNotLike(String value) {
            addCriterion("ACTRESS_NAME not like", value, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameIn(List<String> values) {
            addCriterion("ACTRESS_NAME in", values, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameNotIn(List<String> values) {
            addCriterion("ACTRESS_NAME not in", values, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameBetween(String value1, String value2) {
            addCriterion("ACTRESS_NAME between", value1, value2, "actressName");
            return (Criteria) this;
        }

        public Criteria andActressNameNotBetween(String value1, String value2) {
            addCriterion("ACTRESS_NAME not between", value1, value2, "actressName");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("BIRTHDAY like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("BIRTHDAY not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andHiplineIsNull() {
            addCriterion("HIPLINE is null");
            return (Criteria) this;
        }

        public Criteria andHiplineIsNotNull() {
            addCriterion("HIPLINE is not null");
            return (Criteria) this;
        }

        public Criteria andHiplineEqualTo(String value) {
            addCriterion("HIPLINE =", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotEqualTo(String value) {
            addCriterion("HIPLINE <>", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineGreaterThan(String value) {
            addCriterion("HIPLINE >", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineGreaterThanOrEqualTo(String value) {
            addCriterion("HIPLINE >=", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineLessThan(String value) {
            addCriterion("HIPLINE <", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineLessThanOrEqualTo(String value) {
            addCriterion("HIPLINE <=", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineLike(String value) {
            addCriterion("HIPLINE like", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotLike(String value) {
            addCriterion("HIPLINE not like", value, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineIn(List<String> values) {
            addCriterion("HIPLINE in", values, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotIn(List<String> values) {
            addCriterion("HIPLINE not in", values, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineBetween(String value1, String value2) {
            addCriterion("HIPLINE between", value1, value2, "hipline");
            return (Criteria) this;
        }

        public Criteria andHiplineNotBetween(String value1, String value2) {
            addCriterion("HIPLINE not between", value1, value2, "hipline");
            return (Criteria) this;
        }

        public Criteria andBustIsNull() {
            addCriterion("BUST is null");
            return (Criteria) this;
        }

        public Criteria andBustIsNotNull() {
            addCriterion("BUST is not null");
            return (Criteria) this;
        }

        public Criteria andBustEqualTo(String value) {
            addCriterion("BUST =", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotEqualTo(String value) {
            addCriterion("BUST <>", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustGreaterThan(String value) {
            addCriterion("BUST >", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustGreaterThanOrEqualTo(String value) {
            addCriterion("BUST >=", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustLessThan(String value) {
            addCriterion("BUST <", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustLessThanOrEqualTo(String value) {
            addCriterion("BUST <=", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustLike(String value) {
            addCriterion("BUST like", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotLike(String value) {
            addCriterion("BUST not like", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustIn(List<String> values) {
            addCriterion("BUST in", values, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotIn(List<String> values) {
            addCriterion("BUST not in", values, "bust");
            return (Criteria) this;
        }

        public Criteria andBustBetween(String value1, String value2) {
            addCriterion("BUST between", value1, value2, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotBetween(String value1, String value2) {
            addCriterion("BUST not between", value1, value2, "bust");
            return (Criteria) this;
        }

        public Criteria andWaistlineIsNull() {
            addCriterion("WAISTLINE is null");
            return (Criteria) this;
        }

        public Criteria andWaistlineIsNotNull() {
            addCriterion("WAISTLINE is not null");
            return (Criteria) this;
        }

        public Criteria andWaistlineEqualTo(String value) {
            addCriterion("WAISTLINE =", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotEqualTo(String value) {
            addCriterion("WAISTLINE <>", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineGreaterThan(String value) {
            addCriterion("WAISTLINE >", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineGreaterThanOrEqualTo(String value) {
            addCriterion("WAISTLINE >=", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineLessThan(String value) {
            addCriterion("WAISTLINE <", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineLessThanOrEqualTo(String value) {
            addCriterion("WAISTLINE <=", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineLike(String value) {
            addCriterion("WAISTLINE like", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotLike(String value) {
            addCriterion("WAISTLINE not like", value, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineIn(List<String> values) {
            addCriterion("WAISTLINE in", values, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotIn(List<String> values) {
            addCriterion("WAISTLINE not in", values, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineBetween(String value1, String value2) {
            addCriterion("WAISTLINE between", value1, value2, "waistline");
            return (Criteria) this;
        }

        public Criteria andWaistlineNotBetween(String value1, String value2) {
            addCriterion("WAISTLINE not between", value1, value2, "waistline");
            return (Criteria) this;
        }

        public Criteria andCupIsNull() {
            addCriterion("CUP is null");
            return (Criteria) this;
        }

        public Criteria andCupIsNotNull() {
            addCriterion("CUP is not null");
            return (Criteria) this;
        }

        public Criteria andCupEqualTo(String value) {
            addCriterion("CUP =", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotEqualTo(String value) {
            addCriterion("CUP <>", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupGreaterThan(String value) {
            addCriterion("CUP >", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupGreaterThanOrEqualTo(String value) {
            addCriterion("CUP >=", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupLessThan(String value) {
            addCriterion("CUP <", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupLessThanOrEqualTo(String value) {
            addCriterion("CUP <=", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupLike(String value) {
            addCriterion("CUP like", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotLike(String value) {
            addCriterion("CUP not like", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupIn(List<String> values) {
            addCriterion("CUP in", values, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotIn(List<String> values) {
            addCriterion("CUP not in", values, "cup");
            return (Criteria) this;
        }

        public Criteria andCupBetween(String value1, String value2) {
            addCriterion("CUP between", value1, value2, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotBetween(String value1, String value2) {
            addCriterion("CUP not between", value1, value2, "cup");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("HEIGHT =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("HEIGHT <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("HEIGHT >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("HEIGHT >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("HEIGHT <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("HEIGHT <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("HEIGHT like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("HEIGHT not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("HEIGHT in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("HEIGHT not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("HEIGHT between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("HEIGHT not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHobbyIsNull() {
            addCriterion("HOBBY is null");
            return (Criteria) this;
        }

        public Criteria andHobbyIsNotNull() {
            addCriterion("HOBBY is not null");
            return (Criteria) this;
        }

        public Criteria andHobbyEqualTo(String value) {
            addCriterion("HOBBY =", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotEqualTo(String value) {
            addCriterion("HOBBY <>", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyGreaterThan(String value) {
            addCriterion("HOBBY >", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyGreaterThanOrEqualTo(String value) {
            addCriterion("HOBBY >=", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyLessThan(String value) {
            addCriterion("HOBBY <", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyLessThanOrEqualTo(String value) {
            addCriterion("HOBBY <=", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyLike(String value) {
            addCriterion("HOBBY like", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotLike(String value) {
            addCriterion("HOBBY not like", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyIn(List<String> values) {
            addCriterion("HOBBY in", values, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotIn(List<String> values) {
            addCriterion("HOBBY not in", values, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyBetween(String value1, String value2) {
            addCriterion("HOBBY between", value1, value2, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotBetween(String value1, String value2) {
            addCriterion("HOBBY not between", value1, value2, "hobby");
            return (Criteria) this;
        }

        public Criteria andHomePlaceIsNull() {
            addCriterion("HOME_PLACE is null");
            return (Criteria) this;
        }

        public Criteria andHomePlaceIsNotNull() {
            addCriterion("HOME_PLACE is not null");
            return (Criteria) this;
        }

        public Criteria andHomePlaceEqualTo(String value) {
            addCriterion("HOME_PLACE =", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceNotEqualTo(String value) {
            addCriterion("HOME_PLACE <>", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceGreaterThan(String value) {
            addCriterion("HOME_PLACE >", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("HOME_PLACE >=", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceLessThan(String value) {
            addCriterion("HOME_PLACE <", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceLessThanOrEqualTo(String value) {
            addCriterion("HOME_PLACE <=", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceLike(String value) {
            addCriterion("HOME_PLACE like", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceNotLike(String value) {
            addCriterion("HOME_PLACE not like", value, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceIn(List<String> values) {
            addCriterion("HOME_PLACE in", values, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceNotIn(List<String> values) {
            addCriterion("HOME_PLACE not in", values, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceBetween(String value1, String value2) {
            addCriterion("HOME_PLACE between", value1, value2, "homePlace");
            return (Criteria) this;
        }

        public Criteria andHomePlaceNotBetween(String value1, String value2) {
            addCriterion("HOME_PLACE not between", value1, value2, "homePlace");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNull() {
            addCriterion("ADD_USER is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNotNull() {
            addCriterion("ADD_USER is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserEqualTo(Long value) {
            addCriterion("ADD_USER =", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotEqualTo(Long value) {
            addCriterion("ADD_USER <>", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThan(Long value) {
            addCriterion("ADD_USER >", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("ADD_USER >=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThan(Long value) {
            addCriterion("ADD_USER <", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThanOrEqualTo(Long value) {
            addCriterion("ADD_USER <=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserIn(List<Long> values) {
            addCriterion("ADD_USER in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotIn(List<Long> values) {
            addCriterion("ADD_USER not in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserBetween(Long value1, Long value2) {
            addCriterion("ADD_USER between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotBetween(Long value1, Long value2) {
            addCriterion("ADD_USER not between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andModUserIsNull() {
            addCriterion("MOD_USER is null");
            return (Criteria) this;
        }

        public Criteria andModUserIsNotNull() {
            addCriterion("MOD_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModUserEqualTo(Long value) {
            addCriterion("MOD_USER =", value, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserNotEqualTo(Long value) {
            addCriterion("MOD_USER <>", value, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserGreaterThan(Long value) {
            addCriterion("MOD_USER >", value, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserGreaterThanOrEqualTo(Long value) {
            addCriterion("MOD_USER >=", value, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserLessThan(Long value) {
            addCriterion("MOD_USER <", value, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserLessThanOrEqualTo(Long value) {
            addCriterion("MOD_USER <=", value, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserIn(List<Long> values) {
            addCriterion("MOD_USER in", values, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserNotIn(List<Long> values) {
            addCriterion("MOD_USER not in", values, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserBetween(Long value1, Long value2) {
            addCriterion("MOD_USER between", value1, value2, "modUser");
            return (Criteria) this;
        }

        public Criteria andModUserNotBetween(Long value1, Long value2) {
            addCriterion("MOD_USER not between", value1, value2, "modUser");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("MOD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("MOD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(Date value) {
            addCriterion("MOD_TIME =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(Date value) {
            addCriterion("MOD_TIME <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(Date value) {
            addCriterion("MOD_TIME >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MOD_TIME >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(Date value) {
            addCriterion("MOD_TIME <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(Date value) {
            addCriterion("MOD_TIME <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<Date> values) {
            addCriterion("MOD_TIME in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<Date> values) {
            addCriterion("MOD_TIME not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(Date value1, Date value2) {
            addCriterion("MOD_TIME between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(Date value1, Date value2) {
            addCriterion("MOD_TIME not between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andIsMyIsNull() {
            addCriterion("IS_MY is null");
            return (Criteria) this;
        }

        public Criteria andIsMyIsNotNull() {
            addCriterion("IS_MY is not null");
            return (Criteria) this;
        }

        public Criteria andIsMyEqualTo(Integer value) {
            addCriterion("IS_MY =", value, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyNotEqualTo(Integer value) {
            addCriterion("IS_MY <>", value, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyGreaterThan(Integer value) {
            addCriterion("IS_MY >", value, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_MY >=", value, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyLessThan(Integer value) {
            addCriterion("IS_MY <", value, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyLessThanOrEqualTo(Integer value) {
            addCriterion("IS_MY <=", value, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyIn(List<Integer> values) {
            addCriterion("IS_MY in", values, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyNotIn(List<Integer> values) {
            addCriterion("IS_MY not in", values, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyBetween(Integer value1, Integer value2) {
            addCriterion("IS_MY between", value1, value2, "isMy");
            return (Criteria) this;
        }

        public Criteria andIsMyNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_MY not between", value1, value2, "isMy");
            return (Criteria) this;
        }

        public Criteria andMyStarIsNull() {
            addCriterion("MY_STAR is null");
            return (Criteria) this;
        }

        public Criteria andMyStarIsNotNull() {
            addCriterion("MY_STAR is not null");
            return (Criteria) this;
        }

        public Criteria andMyStarEqualTo(Integer value) {
            addCriterion("MY_STAR =", value, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarNotEqualTo(Integer value) {
            addCriterion("MY_STAR <>", value, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarGreaterThan(Integer value) {
            addCriterion("MY_STAR >", value, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("MY_STAR >=", value, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarLessThan(Integer value) {
            addCriterion("MY_STAR <", value, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarLessThanOrEqualTo(Integer value) {
            addCriterion("MY_STAR <=", value, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarIn(List<Integer> values) {
            addCriterion("MY_STAR in", values, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarNotIn(List<Integer> values) {
            addCriterion("MY_STAR not in", values, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarBetween(Integer value1, Integer value2) {
            addCriterion("MY_STAR between", value1, value2, "myStar");
            return (Criteria) this;
        }

        public Criteria andMyStarNotBetween(Integer value1, Integer value2) {
            addCriterion("MY_STAR not between", value1, value2, "myStar");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("IMG is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("IMG is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("IMG =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("IMG <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("IMG >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("IMG >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("IMG <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("IMG <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("IMG like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("IMG not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("IMG in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("IMG not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("IMG between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("IMG not between", value1, value2, "img");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table actress
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table actress
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}