package com.dengji85.blog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public ArticleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andImgIdIsNull() {
			addCriterion("IMG_ID is null");
			return (Criteria) this;
		}

		public Criteria andImgIdIsNotNull() {
			addCriterion("IMG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andImgIdEqualTo(String value) {
			addCriterion("IMG_ID =", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotEqualTo(String value) {
			addCriterion("IMG_ID <>", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdGreaterThan(String value) {
			addCriterion("IMG_ID >", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdGreaterThanOrEqualTo(String value) {
			addCriterion("IMG_ID >=", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdLessThan(String value) {
			addCriterion("IMG_ID <", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdLessThanOrEqualTo(String value) {
			addCriterion("IMG_ID <=", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdLike(String value) {
			addCriterion("IMG_ID like", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotLike(String value) {
			addCriterion("IMG_ID not like", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdIn(List<String> values) {
			addCriterion("IMG_ID in", values, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotIn(List<String> values) {
			addCriterion("IMG_ID not in", values, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdBetween(String value1, String value2) {
			addCriterion("IMG_ID between", value1, value2, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotBetween(String value1, String value2) {
			addCriterion("IMG_ID not between", value1, value2, "imgId");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2,
					"description");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("ADD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("ADD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("ADD_TIME =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("ADD_TIME <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("ADD_TIME >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ADD_TIME >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("ADD_TIME <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("ADD_TIME <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("ADD_TIME in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("ADD_TIME not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("ADD_TIME between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("ADD_TIME not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddUserIsNull() {
			addCriterion("ADD_USER is null");
			return (Criteria) this;
		}

		public Criteria andAddUserIsNotNull() {
			addCriterion("ADD_USER is not null");
			return (Criteria) this;
		}

		public Criteria andAddUserEqualTo(Long value) {
			addCriterion("ADD_USER =", value, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserNotEqualTo(Long value) {
			addCriterion("ADD_USER <>", value, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserGreaterThan(Long value) {
			addCriterion("ADD_USER >", value, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserGreaterThanOrEqualTo(Long value) {
			addCriterion("ADD_USER >=", value, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserLessThan(Long value) {
			addCriterion("ADD_USER <", value, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserLessThanOrEqualTo(Long value) {
			addCriterion("ADD_USER <=", value, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserIn(List<Long> values) {
			addCriterion("ADD_USER in", values, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserNotIn(List<Long> values) {
			addCriterion("ADD_USER not in", values, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserBetween(Long value1, Long value2) {
			addCriterion("ADD_USER between", value1, value2, "addUser");
			return (Criteria) this;
		}

		public Criteria andAddUserNotBetween(Long value1, Long value2) {
			addCriterion("ADD_USER not between", value1, value2, "addUser");
			return (Criteria) this;
		}

		public Criteria andModTimeIsNull() {
			addCriterion("MOD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModTimeIsNotNull() {
			addCriterion("MOD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModTimeEqualTo(Date value) {
			addCriterion("MOD_TIME =", value, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeNotEqualTo(Date value) {
			addCriterion("MOD_TIME <>", value, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeGreaterThan(Date value) {
			addCriterion("MOD_TIME >", value, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MOD_TIME >=", value, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeLessThan(Date value) {
			addCriterion("MOD_TIME <", value, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeLessThanOrEqualTo(Date value) {
			addCriterion("MOD_TIME <=", value, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeIn(List<Date> values) {
			addCriterion("MOD_TIME in", values, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeNotIn(List<Date> values) {
			addCriterion("MOD_TIME not in", values, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeBetween(Date value1, Date value2) {
			addCriterion("MOD_TIME between", value1, value2, "modTime");
			return (Criteria) this;
		}

		public Criteria andModTimeNotBetween(Date value1, Date value2) {
			addCriterion("MOD_TIME not between", value1, value2, "modTime");
			return (Criteria) this;
		}

		public Criteria andModUserIsNull() {
			addCriterion("MOD_USER is null");
			return (Criteria) this;
		}

		public Criteria andModUserIsNotNull() {
			addCriterion("MOD_USER is not null");
			return (Criteria) this;
		}

		public Criteria andModUserEqualTo(Long value) {
			addCriterion("MOD_USER =", value, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserNotEqualTo(Long value) {
			addCriterion("MOD_USER <>", value, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserGreaterThan(Long value) {
			addCriterion("MOD_USER >", value, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserGreaterThanOrEqualTo(Long value) {
			addCriterion("MOD_USER >=", value, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserLessThan(Long value) {
			addCriterion("MOD_USER <", value, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserLessThanOrEqualTo(Long value) {
			addCriterion("MOD_USER <=", value, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserIn(List<Long> values) {
			addCriterion("MOD_USER in", values, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserNotIn(List<Long> values) {
			addCriterion("MOD_USER not in", values, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserBetween(Long value1, Long value2) {
			addCriterion("MOD_USER between", value1, value2, "modUser");
			return (Criteria) this;
		}

		public Criteria andModUserNotBetween(Long value1, Long value2) {
			addCriterion("MOD_USER not between", value1, value2, "modUser");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("DEL_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("DEL_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Integer value) {
			addCriterion("DEL_FLAG =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Integer value) {
			addCriterion("DEL_FLAG <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Integer value) {
			addCriterion("DEL_FLAG >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEL_FLAG >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Integer value) {
			addCriterion("DEL_FLAG <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
			addCriterion("DEL_FLAG <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Integer> values) {
			addCriterion("DEL_FLAG in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Integer> values) {
			addCriterion("DEL_FLAG not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Integer value1, Integer value2) {
			addCriterion("DEL_FLAG between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNull() {
			addCriterion("VIEW_NUM is null");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNotNull() {
			addCriterion("VIEW_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andViewNumEqualTo(Integer value) {
			addCriterion("VIEW_NUM =", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotEqualTo(Integer value) {
			addCriterion("VIEW_NUM <>", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThan(Integer value) {
			addCriterion("VIEW_NUM >", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("VIEW_NUM >=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThan(Integer value) {
			addCriterion("VIEW_NUM <", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThanOrEqualTo(Integer value) {
			addCriterion("VIEW_NUM <=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumIn(List<Integer> values) {
			addCriterion("VIEW_NUM in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotIn(List<Integer> values) {
			addCriterion("VIEW_NUM not in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumBetween(Integer value1, Integer value2) {
			addCriterion("VIEW_NUM between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotBetween(Integer value1, Integer value2) {
			addCriterion("VIEW_NUM not between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumIsNull() {
			addCriterion("COMMENT_NUM is null");
			return (Criteria) this;
		}

		public Criteria andCommentNumIsNotNull() {
			addCriterion("COMMENT_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andCommentNumEqualTo(Integer value) {
			addCriterion("COMMENT_NUM =", value, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumNotEqualTo(Integer value) {
			addCriterion("COMMENT_NUM <>", value, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumGreaterThan(Integer value) {
			addCriterion("COMMENT_NUM >", value, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("COMMENT_NUM >=", value, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumLessThan(Integer value) {
			addCriterion("COMMENT_NUM <", value, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumLessThanOrEqualTo(Integer value) {
			addCriterion("COMMENT_NUM <=", value, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumIn(List<Integer> values) {
			addCriterion("COMMENT_NUM in", values, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumNotIn(List<Integer> values) {
			addCriterion("COMMENT_NUM not in", values, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumBetween(Integer value1, Integer value2) {
			addCriterion("COMMENT_NUM between", value1, value2, "commentNum");
			return (Criteria) this;
		}

		public Criteria andCommentNumNotBetween(Integer value1, Integer value2) {
			addCriterion("COMMENT_NUM not between", value1, value2,
					"commentNum");
			return (Criteria) this;
		}

		public Criteria andKeyWordsIsNull() {
			addCriterion("KEY_WORDS is null");
			return (Criteria) this;
		}

		public Criteria andKeyWordsIsNotNull() {
			addCriterion("KEY_WORDS is not null");
			return (Criteria) this;
		}

		public Criteria andKeyWordsEqualTo(String value) {
			addCriterion("KEY_WORDS =", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotEqualTo(String value) {
			addCriterion("KEY_WORDS <>", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsGreaterThan(String value) {
			addCriterion("KEY_WORDS >", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsGreaterThanOrEqualTo(String value) {
			addCriterion("KEY_WORDS >=", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsLessThan(String value) {
			addCriterion("KEY_WORDS <", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsLessThanOrEqualTo(String value) {
			addCriterion("KEY_WORDS <=", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsLike(String value) {
			addCriterion("KEY_WORDS like", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotLike(String value) {
			addCriterion("KEY_WORDS not like", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsIn(List<String> values) {
			addCriterion("KEY_WORDS in", values, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotIn(List<String> values) {
			addCriterion("KEY_WORDS not in", values, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsBetween(String value1, String value2) {
			addCriterion("KEY_WORDS between", value1, value2, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotBetween(String value1, String value2) {
			addCriterion("KEY_WORDS not between", value1, value2, "keyWords");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(Integer value) {
			addCriterion("ORDER_NO =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(Integer value) {
			addCriterion("ORDER_NO <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(Integer value) {
			addCriterion("ORDER_NO >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_NO >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(Integer value) {
			addCriterion("ORDER_NO <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_NO <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<Integer> values) {
			addCriterion("ORDER_NO in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<Integer> values) {
			addCriterion("ORDER_NO not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_NO between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_NO not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andRecommendIsNull() {
			addCriterion("RECOMMEND is null");
			return (Criteria) this;
		}

		public Criteria andRecommendIsNotNull() {
			addCriterion("RECOMMEND is not null");
			return (Criteria) this;
		}

		public Criteria andRecommendEqualTo(Integer value) {
			addCriterion("RECOMMEND =", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotEqualTo(Integer value) {
			addCriterion("RECOMMEND <>", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendGreaterThan(Integer value) {
			addCriterion("RECOMMEND >", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendGreaterThanOrEqualTo(Integer value) {
			addCriterion("RECOMMEND >=", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendLessThan(Integer value) {
			addCriterion("RECOMMEND <", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendLessThanOrEqualTo(Integer value) {
			addCriterion("RECOMMEND <=", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendIn(List<Integer> values) {
			addCriterion("RECOMMEND in", values, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotIn(List<Integer> values) {
			addCriterion("RECOMMEND not in", values, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendBetween(Integer value1, Integer value2) {
			addCriterion("RECOMMEND between", value1, value2, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotBetween(Integer value1, Integer value2) {
			addCriterion("RECOMMEND not between", value1, value2, "recommend");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}