package com.dengji85.blog.model;

import java.util.Date;

public class TimeLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_line.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_line.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_line.ADD_TIME
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_line.ADD_USER
     *
     * @mbggenerated
     */
    private Long addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_line.MOD_TIME
     *
     * @mbggenerated
     */
    private Date modTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_line.MOD_USER
     *
     * @mbggenerated
     */
    private Long modUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_line.ID
     *
     * @return the value of time_line.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_line.ID
     *
     * @param id the value for time_line.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_line.CONTENT
     *
     * @return the value of time_line.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_line.CONTENT
     *
     * @param content the value for time_line.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_line.ADD_TIME
     *
     * @return the value of time_line.ADD_TIME
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_line.ADD_TIME
     *
     * @param addTime the value for time_line.ADD_TIME
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_line.ADD_USER
     *
     * @return the value of time_line.ADD_USER
     *
     * @mbggenerated
     */
    public Long getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_line.ADD_USER
     *
     * @param addUser the value for time_line.ADD_USER
     *
     * @mbggenerated
     */
    public void setAddUser(Long addUser) {
        this.addUser = addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_line.MOD_TIME
     *
     * @return the value of time_line.MOD_TIME
     *
     * @mbggenerated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_line.MOD_TIME
     *
     * @param modTime the value for time_line.MOD_TIME
     *
     * @mbggenerated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_line.MOD_USER
     *
     * @return the value of time_line.MOD_USER
     *
     * @mbggenerated
     */
    public Long getModUser() {
        return modUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_line.MOD_USER
     *
     * @param modUser the value for time_line.MOD_USER
     *
     * @mbggenerated
     */
    public void setModUser(Long modUser) {
        this.modUser = modUser;
    }
}